Checking if cf was installed through the bin folder
Because the '-x' argument seems to not be reliable in fedora, we decided
to check for the existence of the cf (cf and cf7) file under the bin folder.

Co-authored-by: Dominic Roberts <dominicr@vmware.com>

diff --git a/ci/shared/tasks/integration-rpm-installers.yml b/ci/shared/tasks/integration-rpm-installers.yml
--- a/ci/shared/tasks/integration-rpm-installers.yml
+++ b/ci/shared/tasks/integration-rpm-installers.yml
@@ -29,6 +29,11 @@ run:
 
     rpm -i "installer/cf${SUFFIX}-cli-installer_edge_${ARCH}.rpm"
 
+    if ! [ -f "$(command -v cf)" ]; then
+      echo 'Error: cf is not installed.' >&2
+      exit 1
+    fi
+
     EXPECTED_CLI_VERSION="$(cat cli/BUILD_VERSION)"
     CF_VERSION="$(cf -v)"
 
@@ -38,7 +43,7 @@ run:
     fi
 
     if ! [ "$MAJOR_VERSION" == "6" ]; then
-      if ! [ -x "$(command -v cf${SUFFIX})" ]; then
+      if ! [ -f "$(command -v cf${SUFFIX})" ]; then
         echo 'Error: cf${SUFFIX} is not installed.' >&2
         exit 1
       fi
